Fix build error under Fedora 38 with 6.4.3
This will hopefully fix:

```
[   56s] /home/abuild/rpmbuild/BUILD/syncthingtray-1718839812.fa5a7b5/redhat-linux-build/syncthingmodel/syncthingmodel-qt6_autogen/EWIEGA46WW/moc_syncthingfilemodel.cpp:177:5:   required from here
[   56s] /usr/include/qt6/QtCore/qmetatype.h:842:23: error: invalid application of 'sizeof' to incomplete type 'QAction'
[   56s]   842 |         static_assert(sizeof(T), "Type argument of Q_PROPERTY or Q_DECLARE_METATYPE(T*) must be fully defined");
```