Clear pending JNI exception when isNetworkConnectionMetered is not found
NOT needed, QJniEnvironment takes care of that.

On Android, the GUI process context is Activity which does not implement
`isNetworkConnectionMetered`. Calling `findMethod` on it throws
`NoSuchMethodError` inside the JVM. This must be cleared to avoid unsafe
JNI state.