Use C/C++/linker flags for Go compilation from environment consistently
* Use flags from CMake's variables (initialized from environment variables)
  including build type specific variables
* Consider LDFLAGS as well; there's actually linking going on¹

¹Otherwise Go's build system wouldn't run into this error

```
# github.com/DataDog/zstd
/usr/lib/gcc/i686-w64-mingw32/10.2.0/../../../../i686-w64-mingw32/bin/ld: $WORK/b259/_x008.o:entropy_common.c:(.text+0xaa): undefined reference to `__memcpy_chk'
/usr/lib/gcc/i686-w64-mingw32/10.2.0/../../../../i686-w64-mingw32/bin/ld: $WORK/b259/_x033.o:zstd_v01.c:(.text+0x1b84): undefined reference to `__memcpy_chk'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```

which is caused by LDFLAGS being inconsistent with CFLAGS.